version: '3.7'

services:
#
# letsencrypt
# This container sets up an Nginx webserver and reverse proxy with php support 
# and a built-in letsencrypt client that automates free SSL server certificate generation and renewal processes. 
# It also contains fail2ban for intrusion prevention.
#
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    privileged: true
    restart: always
    cap_add:
      - NET_ADMIN
    environment:
      - PGID=1000
      - PUID=1000
      - EMAIL=${EMAIL}
      - URL=${URL}
      - EXTRA_DOMAINS=${EXTRA_DOMAINS}
      - DHLEVEL=2048
      - TZ=${TZ}
      - VALIDATION=http
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/centos/letsencrypt:/config
      - /home/centos/lightsail-juiceshop/nginx:/config/nginx/site-confs/default
    depends_on:
      - "no-ip"
      - "juice-shop"
    extra_hosts:
      - "plex:${HOST_IP}"
    networks:
      - app_net
    healthcheck:
     test: ["CMD-SHELL", "curl -f --insecure https://localhost && echo 'OK'"]
     interval: 5s
     timeout: 2s
     retries: 20

#
# no-ip
# This is a simple Docker container for running the No-IP2 dynamic DNS update script. 
# It will keep your domain.ddns.net DNS alias up-to-date as your home IP changes.
#
  no-ip:
    image: coppit/no-ip
    container_name: noip
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
      - /home/centos/noip:/config
      - /home/centos/lightsail-juiceshop/noip.conf:/config/noip.conf
    environment:
      - PGID=1000 #optional
      - PUID=1000 #optional

#
# juice-shop
# OWASP Juice Shop: Probably the most modern and sophisticated insecure web application
#
  juice-shop:
    image: bkimminich/juice-shop
    restart: always
    networks:
      - app_net

#
# network
#
networks:
  app_net:
    driver: bridge
    ipam:
     driver: default
     config:
      - subnet: 172.20.0.0/16
